Vagrant.configure("2") do |c|
  c.vm.define 'centos-65-x64' do |v|
    v.vm.hostname = 'centos-65-x64'
    v.vm.box = 'puppetlabs/puppet-training-centos-6.5-pe-3.3.0'
    v.vm.box_url = 'http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-nocm.box'
    v.vm.box_check_update = 'true'
    v.vm.network :private_network, ip: "10.255.28.252", :netmask => "255.255.0.0", :mac => "080027FBF6D3"
    v.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
    end
  end
end
